export const gaMessage: any = {
    registerNewUser: 'Register New User',
    login: 'Login',
    register: 'Register Completed',
    addInvoiceData: 'Add Invoice',
    updateInvoiceData: 'Update Invoice',
    addDocumentData: 'Add Document',
    updateDocumentData: 'Update Document',
    addGoalData: 'Add Goal',
    updateGoalData: 'Update Goal',
    addTrackGoalData: 'Add TrackGoal',
    updateTrackGoalData: 'Update Track Goal',
    uploadPlanData: 'Upload Plan',
    savePlanData: 'Save Plan',
    updatePlanData: 'Update Plan',
    saveBudgetData: 'Save Budget',
    updateBudgetData: 'Update Budget',
    changePassword: 'Change Password',
    updateProfile: 'Update Profile',
    resetPassword: 'Reset Password',
    deleteInvoiceData: 'Delete Invoice',
    deleteDocumentData: 'Delete Document',
    deleteGoalData: 'Delete Goal',
    deleteTrackGoalData: 'Delete Track Goal',
    deleteBudgetData: 'Delete Budget',
    redirectViewPlan: 'Redirect View',
    redirectToInvoice: 'Redirect To Invoice',
    redirectToGoals: 'Redirect To Goals',
    redirectToAppointments: 'Redirect To Appointments',
    redirectToMyserviceProvider: 'Redirect To Myservice Provider'
};

